title: Sin.Net
author: Adrian Singer
email: adriansinger87@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Site for projects and blog post

github_username:  adriansinger87

sass:
    style: compressed