title: Sin.Net
claim: '{Code} [Blog] _Live_'
author: Adrian Singer
email: adriansinger87@gmail.com
description: >
  A Site for projects and blog post

github_username:  adriansinger87

future: false

sass:
    style: compressed

highlighter: rouge

permalink: /:categories/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-feed